# The transfer portal identifies SINAN file families by these official
# acronyms. Existing descriptive identifiers remain unchanged for compatibility;
# newly supported families use the acronym directly to avoid invented aliases.
.sinan_system_specs <- function() {
  information_system <- c(
    ANIM = "SINAN-ANIM",
    ANTR = "SINAN-ANTR",
    AIDA = "SINAN-AIDA",
    AIDC = "SINAN-AIDC",
    BOTU = "SINAN-BOTU",
    COLE = "SINAN-COLE",
    COQU = "SINAN-COQU",
    DENG = "SINAN-DENGUE",
    DIFT = "SINAN-DIFT",
    DCRJ = "SINAN-DCRJ",
    CHAG = "SINAN-CHAGAS",
    EXAN = "SINAN-EXAN",
    ESQU = "SINAN-ESQU",
    ESPO = "SINAN-ESPO",
    CHIK = "SINAN-CHIKUNGUNYA",
    FMAC = "SINAN-FMAC",
    FTIF = "SINAN-FTIF",
    HANS = "SINAN-HANS",
    HANT = "SINAN-HANT",
    HEPA = "SINAN-HEPA",
    HIVA = "SINAN-HIVA",
    HIVC = "SINAN-HIVC",
    HIVE = "SINAN-HIVE",
    HIVG = "SINAN-HIVG",
    INFL = "SINAN-INFL",
    IEXO = "SINAN-IEXO",
    LEIV = "SINAN-LEISHMANIOSE-VISCERAL",
    LTAN = "SINAN-LEISHMANIOSE-TEGUMENTAR",
    LEPT = "SINAN-LEPTOSPIROSE",
    MALA = "SINAN-MALARIA",
    MENI = "SINAN-MENI",
    PFAN = "SINAN-PFAN",
    PEST = "SINAN-PEST",
    RAIV = "SINAN-RAIV",
    ROTA = "SINAN-ROTA",
    SIFA = "SINAN-SIFA",
    SIFC = "SINAN-SIFC",
    SIFG = "SINAN-SIFG",
    SRC = "SINAN-SRC",
    SDTA = "SINAN-SDTA",
    TETA = "SINAN-TETA",
    TETN = "SINAN-TETN",
    TOXC = "SINAN-TOXC",
    TOXG = "SINAN-TOXG",
    NTRA = "SINAN-NTRA",
    TRAC = "SINAN-TRAC",
    TUBE = "SINAN-TUBE",
    VARC = "SINAN-VARC",
    VIOL = "SINAN-VIOL",
    ZIKA = "SINAN-ZIKA",
    ACBI = "SINAN-ACBI",
    ACGR = "SINAN-ACGR",
    CANC = "SINAN-CANC",
    DERM = "SINAN-DERM",
    LERD = "SINAN-LERD",
    PAIR = "SINAN-PAIR",
    PNEU = "SINAN-PNEU",
    MENT = "SINAN-MENT"
  )
  definitions <- c(
    ANIM = "AnimaispNET.DEF",
    ANTR = "AntirabNET.def",
    AIDA = "AidsNET.def",
    AIDC = "AidsCriNET.def",
    BOTU = "BotuNET.def",
    COLE = "ColeraNET.def",
    COQU = "CoqueNET.def",
    DENG = "DengueNETON3.0.def",
    DIFT = "DifteriNET.def",
    DCRJ = "NotIndiviNet.def",
    CHAG = "ChagasNET2.def",
    EXAN = "ExantNET.def",
    ESQU = "EsquisNET.def",
    ESPO = "EpizotNet.def",
    CHIK = "ChikNON.def",
    FMAC = "FMacNet.def",
    FTIF = "FTifoideNET.def",
    HANS = "HansNET.def",
    HANT = "HantaNET.def",
    HEPA = "HepavirNET.def",
    HIVA = "NotIndiviNet.def",
    HIVC = "NotIndiviNet.def",
    HIVE = "NotIndiviNet.def",
    HIVG = "HivGestNET.def",
    INFL = "InfluenzaNET.def",
    IEXO = "IntoxNET.def",
    LEIV = "LeishvisNET.def",
    LTAN = "LeishtegNET.def",
    LEPT = "LeptoNET.def",
    MALA = "MalariaNET.def",
    MENI = "MeningeNET.def",
    PFAN = "PfapolioNET.def",
    PEST = "PesteNET.def",
    RAIV = "RaivaNET.def",
    ROTA = "ROTANet.def",
    SIFA = "NotIndiviNet.def",
    SIFC = "SifilisNET.def",
    SIFG = "GestSifNET.def",
    SRC = "SrcNET.def",
    SDTA = "DTANet.def",
    TETA = "TetacidNET.def",
    TETN = "TetneoNET.def",
    TOXC = "NotIndiviNet.def",
    TOXG = "NotIndiviNet.def",
    NTRA = "NotTracoNet.def",
    TRAC = "TracoNet.def",
    TUBE = "TuberculNET5_0.def",
    VARC = "NotIndiviNet.def",
    VIOL = "ViolenciaNet.def",
    ZIKA = "NotIndiviNet.def",
    ACBI = "AcidBioNET.def",
    ACGR = "AcidGraveNET.def",
    CANC = "DRTCancerNET.def",
    DERM = "DRTDermatoseNET.def",
    LERD = "DRTLerDortNET.def",
    PAIR = "DRTPairNET.def",
    PNEU = "DRTPneumoconioseNET.def",
    MENT = "DRTTransMentalNET.def"
  )
  acronyms <- names(information_system)
  online <- acronyms %in% c("DENG", "CHIK")
  data.frame(
    information_system = unname(information_system),
    acronym = acronyms,
    prefix = paste0(acronyms, "BR"),
    definition = unname(definitions[acronyms]),
    archive = ifelse(online, "SINAN-ONLINE", "SINAN-NET"),
    stringsAsFactors = FALSE,
    row.names = unname(information_system)
  )
}

.sinan_information_systems <- function() {
  .sinan_system_specs()$information_system
}
